name: Destroy-Infra

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  destroy:
    if: github.ref == 'main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        working-directory: ./
        run: terraform init
      - name: Terraform Destroy
        working-directory: ./
        run: terraform destroy -auto-approve
