name: Destroy-Infra

on:
  pull_request:
    types: [closed]
    branches:
      - staging-branch
      
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Format Terraform code
        working-directory: ./
        run: terraform fmt

  destroy:
    needs: lint
    if: github.ref == 'staging-branch' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform init
      run: terraform init 
      working-directory: ./
    - name: Terraform Destroy
      working-directory: ./
      run: terraform destroy -auto-approve