name: Terraform CI/CD

on:
  push:
    branches:
      - dev-branch
      

  pull_request:
    types: [closed]
    branches:
      - main
      - staging-branch
      
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
      - name: Format Terraform code
        working-directory: ./
        run: terraform fmt
        
  plan:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev-branch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6
    - name: Terraform init
      working-directory: ./
      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
    - name: Terraform Plan
      working-directory: ./
      run: terraform plan

  apply:
    needs: lint
    if: github.ref == 'main' && github.event.pull_request.merged == true   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6
    - name: Terraform init
      working-directory: ./
      run: terraform init
    - name: Terraform Apply
      working-directory: ./
      run: terraform apply -auto-approve

  destroy:
    needs: lint
    if: github.ref == 'staging-branch' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6
    - name: Terraform init
      run: terraform init 
      working-directory: ./
    - name: Terraform Destroy
      working-directory: ./
      run: terraform destroy -auto-approve