name: Server Deploy

on:
  push:
    branches: ['staging-branch']

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      
