Name: Server Deploy

on: 
  pull_request:
     types: [closed]
     branches:
      - main

jobs:
  deploy-server:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          sudo ssh -i ~/.ssh/key.pem ubuntu@ip-------
          cd /home/ubuntu
          git clone https://github.com/eabrahym75/MERN-store.git
          cd MERN-store/
          cd backend/
          sudo npm install
          sudo kill $(lsof -nt -i4TCP:8000)
          sudo pm2 run build
          cd frontend/     
          sudo npm install
          sudo kill $(lsof -nt -i4TCP:3000)
          sudo pm2 run build                             
          cd socket/  
          sudo npm install
          sudo kill $(lsof -nt -i4TCP:4000)
          sudo pm2 run build    
          sudo pm2 delete react-build || true
          pm2 serve build/ 3000 -f --name "react-build" --spa
          sudo systemctl restart nginx

