name: Server Deploy

on:
  push:
    branches: ['staging-branch']

jobs:
  deploy-server:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          

sudo ssh -i ~/.ssh/key.pem ubuntu@ip-------


cd /home/ubuntu
sudo rm -rf server || true
sudo git clone <git url>
cd full-ecommerce/
cd web_services
sudo npm install
sudo pm2 kill
sudo kill $(lsof -nt -i4TCP:5002)
sudo pm2 start index.js --name "backend-server"
sudo rm -rf /etc/nginx/sites-available/default
sudo cp server-config /etc/nginx/sites-available/ -r
sudo systemctl kill nginx || true
sudo systemctl start nginx