Name: Server Deploy

on: 
  pull_request:
     types: [closed]
     branches:
      - main

jobs:
  deploy-server:
    runs-on: self-hosted
    needs: Terraform CI/CD
    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          envs: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |-
            ssh -i secrets.SSH_PRIVATE_KEY secrets.USER@secrets.HOST
            cd /home/ubuntu \
            git clone https://github.com/eabrahym75/MERN-store.git 
            cd MERN-store/
            cd backend/
            sudo npm install
            sudo npm install mongodb
            sudo kill $(lsof -nt -i4TCP:8000)
            sudo pm2 run dev
            cd ..  \
            cd frontend/     
            sudo yarn install
            sudo kill $(lsof -nt -i4TCP:3000)
            sudo pm2 run build 
            sudo rm -rf /var/www/html
            sudo mkdir /var/www/html
            sudo cp build/* /var/www/html -r 
            cd .. \                          
            cd socket/  
            sudo npm install
            sudo kill $(lsof -nt -i4TCP:4000)
            sudo pm2 start 
            sudo pm2 delete react-build || true
            pm2 serve build/ 3000 -f --name "react-build" --spa
            sudo systemctl restart nginx



